name: Build RMX1901-Kernel
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TELEGRAM_TO: "${{ secrets.TELEGRAM_TO }}"
      TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_DEFCONFIG: "sdm670-perf_defconfig"
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        submodules: 'true'
        fetch-depth: 0

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2.16
    
    - name: Install dependencies
      id: version
      run: |
        sudo timedatectl set-timezone Asia/Kolkata
        sudo apt-get update -y
        sudo apt install gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi binutils make python3 libssl-dev build-essential bc bison flex zip unzip ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y
        
        # Clone toolchains
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang
        git clone https://github.com/shravansayz/AnyKernel3.git -b master --depth=1
        
        # Clean AnyKernel3
        rm -rf AnyKernel3/.git AnyKernel3/.github
        
        # Setup KernelSU
        cd KernelSU-Next
        git checkout next
        git pull
        export VERSION=$(git rev-list --count HEAD)
        echo "VER=$(($VERSION + 10200))" >> $GITHUB_OUTPUT
        cd ..
        
        # Integrate KernelSU
        ./KernelSU-Next/scripts/setup.sh kernelSU
        
        git submodule sync
        git submodule update --init --recursive
    
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=GMT+06 date +%m%d%H%M)" >> $GITHUB_OUTPUT
    
    - name: Build Kernel
      run: |
        export PATH=$(pwd)/clang/bin:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        export CLANG_PATH=$(pwd)/clang/bin
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
        export LLVM=1
        export LLVM_IAS=1
        
        # Build configuration
        make O=out $KERNEL_DEFCONFIG
        
        # Build kernel
        make O=out CC="ccache clang" -j$(nproc --all)
        
        # Copy output
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        ls -la AnyKernel3/

    - name: Upload Kernel
      uses: actions/upload-artifact@v4.6.0
      with:
        name: RMX1901-KernelSU-Next-${{ steps.version.outputs.VER }}-${{ steps.get_time.outputs.TIME }}
        path: AnyKernel3/Image.gz-dtb
